services:
  app:
    image: laravelsail/php82-composer
    container_name: accessibility_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:8000"
    command: sleep infinity

  db:
    image: mysql:8
    container_name: accessibility_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accessibility_app
    ports:
      - "3307:3306"